services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: edu_user
      POSTGRES_PASSWORD: edu_pass
      POSTGRES_DB: edu_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://edu_user:edu_pass@db:5432/edu_db
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://api:4000
      NODE_ENV: production
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
